### Data Cleaning in pandas

* Check for any duplicates and if any removv them
* Standardisze data and fix error

In [176]:
import pandas as pd

In [177]:
# import dstaset
df = pd.read_excel(r"C:\Users\klemp\OneDrive\Documents\aditya vs\datasets (1)\ccl.xlsx")

In [124]:
df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True

In [125]:
type(df)

pandas.core.frame.DataFrame

In [178]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
dtype: bool

In [127]:
df.iloc[20]

CustomerID                                  1020
First_Name                                Anakin
Last_Name                              Skywalker
Phone_Number                        876|678|3469
Address              910 Tatooine Road, Tatooine
Paying Customer                              Yes
Do_Not_Contact                                 N
Not_Useful_Column                           True
Name: 20, dtype: object

In [128]:
df.tail(5)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [129]:
fd = df.duplicated()

In [130]:
df[fd]

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [179]:
df.drop_duplicates(inplace=True)

In [132]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [133]:
df.duplicated().sum()

np.int64(0)

Step 2

In [134]:
df.columns

Index(['CustomerID', 'First_Name', 'Last_Name', 'Phone_Number', 'Address',
       'Paying Customer', 'Do_Not_Contact', 'Not_Useful_Column'],
      dtype='object')

In [135]:
df['Last_Name']

0         Baggins
1           Nadir
2          /White
3         Schrute
4            Snow
5         Swanson
6          Winger
7          Holmes
8             NaN
9          Parker
10         Gamgee
11      ...Potter
12         Draper
13          Knope
14    Flenderson_
15        Weasley
16          Scott
17           Kent
18         Braton
19      Skywalker
Name: Last_Name, dtype: object

In [136]:
ln = "...Potter"
ln.strip()

'...Potter'

In [180]:
df['Last_Name'] = df['Last_Name'].str.strip("123._/")

In [181]:

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

# steps to make all numbers in one phone number column to be same length
#step1 - replace all the unwanted charecters to empty string ("")

In [139]:
name = "Aditya-Kumar"
type(name)
name.replace("-"," ")

name[0:4]+"/"+name[4:]

'Adit/ya-Kumar'

In [182]:
df['Phone_Number'] = df['Phone_Number'].str.replace("[^0-9]","",regex=True)

In [183]:
l1 = lambda x:x[0:3]+"-"+x[3:6]+"-"+x[6:10] ##lambda function to format phone number
l1("1234567890")

'123-456-7890'

In [146]:
name = "mike-tyson"
type(name)
name.replace("-"," ")
name[0:4]+"/"+name[4:10]

'mike/-tyson'

In [147]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes,False
2,1003,Walter,White,nan,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,nan,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,nan,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,nan,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,nan,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N,True

In [148]:
df['Paying Customer'].str.replace('Yes' ,"Y")

0       Y
1      No
2       N
3       Y
4       Y
5       Y
6      No
7       N
8       Y
9       Y
10      Y
11      Y
12      Y
13      Y
14      N
15     No
16      Y
17      Y
18    N/a
19      Y
Name: Paying Customer, dtype: object

In [149]:
### apply() => Apply is a pandas function which will apply  specifies functionality to each valu of series
df['Phone_Number'].apply(lambda x : str(x))

0     1235455421
1     1236439775
2            nan
3     1235432345
4     8766783469
5     3047622467
6            nan
7     8766783469
8
9     1235455421
10           nan
11           nan
12    1235432345
13    8766783469
14    3047622467
15    1235455421
16    1236439775
17           nan
18
19    8766783469
Name: Phone_Number, dtype: object

In [150]:
df['Phone_Number']=df['Phone_Number'].apply(lambda x : x[0:3]+"-"+x[3:6]+"-"+x[6:10])

In [151]:
df['Do_Not_Contact']=df['Do_Not_Contact'].str.replace("Yes","Y")
df['Do_Not_Contact']=df['Do_Not_Contact'].str.replace("No","N")

In [152]:
df['Phone_Number']=df['Phone_Number'].str.replace("--","")

In [175]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,12354554,"123 Shire Lane, Shire",Yes,N,True
1,1002,Abed,Nadir,12364397,93 West Main Street,No,Y,False
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,12354323,"980 Paper Avenue, Pennsylvania,8503",Yes,Y,True
4,1005,Jon,Snow,87667834,123 Dragons Road,Y,N,True
5,1006,Ron,Swanson,30476224,768 City Parkway,Yes,Y,True
6,1007,Jeff,Winger,,1209 South Street,No,N,False
7,1008,Sherlock,Holmes,87667834,98 Clue Drive,N,N,False
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,12354554,"25th Main Street, New York",Yes,N,True
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,N,True
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,12354323,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,87667834,343 City Parkway,Yes,N,False
14,1015,Toby,Flenderson,30476224,214 HR Avenue,N,N,False
15,1016,Ron,Weasley,12354554,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,12364397,"121 Paper Avenue, Pennsylvania",Yes,N,False
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,,N/a,N/a,Y,True
19,1020,Anakin,Skywalker,87667834,"910 Tatooine Road, Tatooine",Yes,N,True

In [154]:
df['Do_Not_Contact']

0       N
1       Y
2     NaN
3       Y
4       N
5       Y
6       N
7       N
8     NaN
9       N
10      N
11    NaN
12      N
13      N
14      N
15      N
16      N
17    NaN
18      Y
19      N
Name: Do_Not_Contact, dtype: object

In [155]:
df['Phone_Number'] = df['Phone_Number'].astype(str).apply(l1)

In [156]:
df['Address']

0                     123 Shire Lane, Shire
1                       93 West Main Street
2                        298 Drugs Driveway
3     980 Paper Avenue, Pennsylvania, 18503
4                          123 Dragons Road
5                          768 City Parkway
6                         1209 South Street
7                             98 Clue Drive
8                          123 Middle Earth
9                25th Main Street, New York
10                    612 Shire Lane, Shire
11                     2394 Hogwarts Avenue
12                         2039 Main Street
13                         343 City Parkway
14                            214 HR Avenue
15                     2395 Hogwarts Avenue
16           121 Paper Avenue, Pennsylvania
17                          3498 Super Lane
18                                      N/a
19              910 Tatooine Road, Tatooine
Name: Address, dtype: object

In [169]:

df['Address'] = df['Address'].str.replace(" [^a-zA-Z]", "", regex=True)

In [170]:
fullname = "Rohit,Sharma"
fullname.split(",")

['Rohit', 'Sharma']

In [171]:
df['Address'].str.split(",")

0                    [123 Shire Lane,  Shire]
1                       [93 West Main Street]
2                        [298 Drugs Driveway]
3     [980 Paper Avenue,  Pennsylvania, 8503]
4                          [123 Dragons Road]
5                          [768 City Parkway]
6                         [1209 South Street]
7                             [98 Clue Drive]
8                          [123 Middle Earth]
9               [25th Main Street,  New York]
10                   [612 Shire Lane,  Shire]
11                     [2394 Hogwarts Avenue]
12                         [2039 Main Street]
13                         [343 City Parkway]
14                            [214 HR Avenue]
15                     [2395 Hogwarts Avenue]
16          [121 Paper Avenue,  Pennsylvania]
17                          [3498 Super Lane]
18                                      [N/a]
19             [910 Tatooine Road,  Tatooine]
Name: Address, dtype: object

In [172]:
df['Address'].str.split(',', expand=True)

                       0              1     2
0         123 Shire Lane          Shire  None
1    93 West Main Street           None  None
2     298 Drugs Driveway           None  None
3       980 Paper Avenue   Pennsylvania  8503
4       123 Dragons Road           None  None
5       768 City Parkway           None  None
6      1209 South Street           None  None
7          98 Clue Drive           None  None
8       123 Middle Earth           None  None
9       25th Main Street       New York  None
10        612 Shire Lane          Shire  None
11  2394 Hogwarts Avenue           None  None
12      2039 Main Street           None  None
13      343 City Parkway           None  None
14         214 HR Avenue           None  None
15  2395 Hogwarts Avenue           None  None
16      121 Paper Avenue   Pennsylvania  None
17       3498 Super Lane           None  None
18                   N/a           None  None
19     910 Tatooine Road       Tatooine  None

In [173]:
df['Address'].str.split(',', expand=True)

                       0              1     2
0         123 Shire Lane          Shire  None
1    93 West Main Street           None  None
2     298 Drugs Driveway           None  None
3       980 Paper Avenue   Pennsylvania  8503
4       123 Dragons Road           None  None
5       768 City Parkway           None  None
6      1209 South Street           None  None
7          98 Clue Drive           None  None
8       123 Middle Earth           None  None
9       25th Main Street       New York  None
10        612 Shire Lane          Shire  None
11  2394 Hogwarts Avenue           None  None
12      2039 Main Street           None  None
13      343 City Parkway           None  None
14         214 HR Avenue           None  None
15  2395 Hogwarts Avenue           None  None
16      121 Paper Avenue   Pennsylvania  None
17       3498 Super Lane           None  None
18                   N/a           None  None
19     910 Tatooine Road       Tatooine  None

In [174]:
df['Do_Not_Contact']

0       N
1       Y
2     NaN
3       Y
4       N
5       Y
6       N
7       N
8     NaN
9       N
10      N
11    NaN
12      N
13      N
14      N
15      N
16      N
17    NaN
18      Y
19      N
Name: Do_Not_Contact, dtype: object

In [163]:
df['Phone_Number'].apply(lambda x : str(x))
df['Phone_Number'] = df['Phone_Number'].str.replace("[^0-9]","",regex=True)

In [164]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,12354554,"123 Shire Lane, Shire",Yes,N,True
1,1002,Abed,Nadir,12364397,93 West Main Street,No,Y,False
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,12354323,"980 Paper Avenue, Pennsylvania,8503",Yes,Y,True
4,1005,Jon,Snow,87667834,123 Dragons Road,Y,N,True
5,1006,Ron,Swanson,30476224,768 City Parkway,Yes,Y,True
6,1007,Jeff,Winger,,1209 South Street,No,N,False
7,1008,Sherlock,Holmes,87667834,98 Clue Drive,N,N,False
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,12354554,"25th Main Street, New York",Yes,N,True
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,N,True
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,12354323,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,87667834,343 City Parkway,Yes,N,False
14,1015,Toby,Flenderson,30476224,214 HR Avenue,N,N,False
15,1016,Ron,Weasley,12354554,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,12364397,"121 Paper Avenue, Pennsylvania",Yes,N,False
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,,N/a,N/a,Y,True
19,1020,Anakin,Skywalker,87667834,"910 Tatooine Road, Tatooine",Yes,N,True

In [165]:
df.to_csv('datasets (1)/cleaned_ccl.xlsx')

In [166]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,12354554,"123 Shire Lane, Shire",Yes,N,True
1,1002,Abed,Nadir,12364397,93 West Main Street,No,Y,False
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,12354323,"980 Paper Avenue, Pennsylvania,8503",Yes,Y,True
4,1005,Jon,Snow,87667834,123 Dragons Road,Y,N,True
5,1006,Ron,Swanson,30476224,768 City Parkway,Yes,Y,True
6,1007,Jeff,Winger,,1209 South Street,No,N,False
7,1008,Sherlock,Holmes,87667834,98 Clue Drive,N,N,False
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,12354554,"25th Main Street, New York",Yes,N,True
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,N,True
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,12354323,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,87667834,343 City Parkway,Yes,N,False
14,1015,Toby,Flenderson,30476224,214 HR Avenue,N,N,False
15,1016,Ron,Weasley,12354554,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,12364397,"121 Paper Avenue, Pennsylvania",Yes,N,False
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,,N/a,N/a,Y,True
19,1020,Anakin,Skywalker,87667834,"910 Tatooine Road, Tatooine",Yes,N,True

In [167]:
df.reset_index(inplace=True,drop=True)

In [168]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,12354554,"123 Shire Lane, Shire",Yes,N,True
1,1002,Abed,Nadir,12364397,93 West Main Street,No,Y,False
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,12354323,"980 Paper Avenue, Pennsylvania,8503",Yes,Y,True
4,1005,Jon,Snow,87667834,123 Dragons Road,Y,N,True
5,1006,Ron,Swanson,30476224,768 City Parkway,Yes,Y,True
6,1007,Jeff,Winger,,1209 South Street,No,N,False
7,1008,Sherlock,Holmes,87667834,98 Clue Drive,N,N,False
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,12354554,"25th Main Street, New York",Yes,N,True
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,N,True
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,12354323,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,87667834,343 City Parkway,Yes,N,False
14,1015,Toby,Flenderson,30476224,214 HR Avenue,N,N,False
15,1016,Ron,Weasley,12354554,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,12364397,"121 Paper Avenue, Pennsylvania",Yes,N,False
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,,N/a,N/a,Y,True
19,1020,Anakin,Skywalker,87667834,"910 Tatooine Road, Tatooine",Yes,N,True

### Line chart 

> To show trends over time or continuos data

> Great for time Seres Data 

>